### ISSUE TITLE
Can't push multiple local languages

### ISSUE THREAD

**Issue by bertmeeuws** [robrechtme/loco-cli#14]
Hi

I am using namespaces, I have 4 folders (nl, fr, en, de) but I want to push and it only uses my default language.
What's the easiest way to push all languages?

**Comment by robrechtme** [comment]
Hi!
That is indeed a limitation of v1.

Feel free to checkout v2 and let me know if that works for you: https://github.com/robrechtme/loco-cli/tree/develop

```
npm i -D loco-cli@next
```
