### ISSUE TITLE
TypeError: Cannot read property 'delete-absent' of undefined

### ISSUE THREAD

**Issue by EfrosIonelu** [robrechtme/loco-cli#17]
When i run in console: **npx loco-cli push**

Error  **"TypeError: Cannot read property 'delete-absent' of undefined"** appear.

Thanks.

**Comment by EfrosIonelu** [comment]
"push": {
    "flag-new": "provisional",
    "delete-absent": false
  }

was added in .locorc.json

**Comment by robrechtme** [comment]
This was a bug, you should be able to use the CLI without adding `push` options in `.locorc`. This is fixed in [v2.0.1](https://github.com/robrechtme/loco-cli/releases/tag/v2.0.1).
