### ISSUE TITLE
Support .cjs file extension

### ISSUE THREAD

**Issue by darthf1** [robrechtme/loco-cli#23]
Hi!

I was wondering if it would be possible to allow the `.cjs` extension for the config file? So  `.locorc.js` can also become `.locorc.cjs`. 

- Example PR eslint: https://github.com/eslint/eslint/issues/14170
- https://eslint.org/docs/latest/user-guide/configuring/configuration-files#configuration-file-formats
- https://babeljs.io/docs/en/config-files#supported-file-extensions

**Comment by robrechtme** [comment]
Hi

For the [v2.1.1](https://github.com/robrechtme/loco-cli/releases/tag/v2.1.1) release I migrated to cosmiconfig, which should support `.cjs` out of the box! 
Feel free to try it out:
```
npm i loco-cli@next
```

**Comment by darthf1** [comment]
Ah yes, that works great! Thanks.
