### ISSUE TITLE
When only one locale is present on loco, `pull` creates namespaces regardless of the `namespaces` flag

### ISSUE THREAD

**Issue by haveneersrobin** [robrechtme/loco-cli#24]
Hello, first of all: thanks for the nice tool 😀

I've found a little bug while using it with only 1 locale.

### Steps to reproduce
- Create a loco project with only 1 locale, for example English
- Create a localisation file in your project, `en.json`
- Push with `loco-cli push` either having `namespaces: false` in your config or by providing it to the cli
- Next, do `loco-cli pull` ...

###  Expected result
- No changes need to be made (as you have just pushed all the translations)

###  Actual result
- The tool creates namespaces based on the 'root' keys of your translations file, instead of notifying that everything is fine.

<img width="661" alt="Screenshot 2022-10-13 at 14 54 54" src="https://user-images.githubusercontent.com/7559898/195602192-0803f783-8ca9-487a-a9ad-8dcfc9c9f693.png">

**Comment by robrechtme** [comment]
Released in v2.1.2 🎉
