### ISSUE TITLE
feature request: pull specific tag

### ISSUE THREAD

**Issue by darthf1** [robrechtme/loco-cli#7]
Hi!

For pushing it's already possible; I would like to be able to retrieve translations only for a specific tag.

I have a monorepo app for which all translations are in the same localise project. Each project in my codebase corresponds to a specific tag in localise.

So:
```shell
npx loco-cli pull
```
To:
```shell
npx loco-cli pull --tag my-tag
```
Equal to push command:
```shell
npx loco-cli push --tag my-tag
```

**Comment by robrechtme** [comment]
Hi! This is actually a great suggestion. I will look into it, or if you want you can open an MR 🙂

**Comment by robrechtme** [comment]
Hi, this feature will be added in v2 🎉. You now have access to all `push` and `pull` options from the Loco API:

```json
{
  "push": {
    "tag-new": "my-tag",
  },
  "pull": {
    "filter": "my-tag"
  }
}
```

The new version is currently in RC, but you can already test it out. See the [Release Notes here](https://github.com/robrechtme/loco-cli/releases/tag/v2.0.0-rc2)
