### ISSUE TITLE
feature request: skip empty translations

### ISSUE THREAD

**Issue by darthf1** [robrechtme/loco-cli#9]
Hi!

Another request :)

It would be great if empty strings can be skipped when pulled (with e.g. a `--skip-empty` argument). For me, these are "untranslated", but because they are pulled as an empty string my app thinks its translated and displays that empty string.

Not sure if the underlying API package permits that.

**Comment by robrechtme** [comment]
Hi

I'm not sure if this is something I want to add as this is kind of a hack. Personally, I would use Loco tags or flags to denote untranslated assets. We can then maybe filter on tags when pulling.

**Comment by darthf1** [comment]
I agree, filtering on tags / flags would be more beneficial.
